---
kind: pipeline
type: kubernetes
name: default

trigger:
 branch:
 - main

steps:
- name: publish
  image: plugins/kaniko-ecr
  environment:
    BUILD_ARGS:
      from_secret: MONGODB_ARGS
  settings:
    create_repository: true
    registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
    repo: sa-demo/${DRONE_REPO_NAME}/all-in-one
    dockerfile: Dockerfile
    context: .
    tags:
      - git-${DRONE_COMMIT_SHA:0:7}
      - latest
    access_key:
      from_secret: ecr_access_key
    secret_key:
      from_secret: ecr_secret_key
    build_args:
      - BUILD_ARGS
  when:
    event:
    - push

- name: deploy
  image: public.ecr.aws/kanopy/drone-helm:v3
  settings:
    chart: mongodb/web-app
    chart_version: 4.25.0
    add_repos: [mongodb=https://10gen.github.io/helm-charts]
    namespace: sa-demo
    release: device-manager
    values_files: [ "environments/base.yaml", "environments/backend.staging.yaml" ]
    values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/sa-demo/${DRONE_REPO_NAME}/all-in-one,ingress.enabled=true,ingress.hosts[0]=device-manager.sa-demo.staging.corp.mongodb.com,mesh.enabled=true
    api_server: https://api.staging.corp.mongodb.com
    kubernetes_token:
      from_secret: staging_kubernetes_token
  when:
    event:
    - push