// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.4
// source: processor.proto

package processor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateDemoMetadataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceNumber      int32 `protobuf:"varint,1,opt,name=deviceNumber,proto3" json:"deviceNumber,omitempty"`
	DeviceParamNumber int32 `protobuf:"varint,2,opt,name=deviceParamNumber,proto3" json:"deviceParamNumber,omitempty"`
}

func (x *GenerateDemoMetadataReq) Reset() {
	*x = GenerateDemoMetadataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDemoMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDemoMetadataReq) ProtoMessage() {}

func (x *GenerateDemoMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDemoMetadataReq.ProtoReflect.Descriptor instead.
func (*GenerateDemoMetadataReq) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDemoMetadataReq) GetDeviceNumber() int32 {
	if x != nil {
		return x.DeviceNumber
	}
	return 0
}

func (x *GenerateDemoMetadataReq) GetDeviceParamNumber() int32 {
	if x != nil {
		return x.DeviceParamNumber
	}
	return 0
}

type GenerateDemoMetadataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GenerateDemoMetadataResp) Reset() {
	*x = GenerateDemoMetadataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDemoMetadataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDemoMetadataResp) ProtoMessage() {}

func (x *GenerateDemoMetadataResp) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDemoMetadataResp.ProtoReflect.Descriptor instead.
func (*GenerateDemoMetadataResp) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDemoMetadataResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type UpdateMetadataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceNumber      int32 `protobuf:"varint,1,opt,name=deviceNumber,proto3" json:"deviceNumber,omitempty"`
	DeviceParamNumber int32 `protobuf:"varint,2,opt,name=deviceParamNumber,proto3" json:"deviceParamNumber,omitempty"`
	Thread            int32 `protobuf:"varint,3,opt,name=thread,proto3" json:"thread,omitempty"`
	Seconds           int32 `protobuf:"varint,4,opt,name=seconds,proto3" json:"seconds,omitempty"`
}

func (x *UpdateMetadataReq) Reset() {
	*x = UpdateMetadataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataReq) ProtoMessage() {}

func (x *UpdateMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataReq.ProtoReflect.Descriptor instead.
func (*UpdateMetadataReq) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetadataReq) GetDeviceNumber() int32 {
	if x != nil {
		return x.DeviceNumber
	}
	return 0
}

func (x *UpdateMetadataReq) GetDeviceParamNumber() int32 {
	if x != nil {
		return x.DeviceParamNumber
	}
	return 0
}

func (x *UpdateMetadataReq) GetThread() int32 {
	if x != nil {
		return x.Thread
	}
	return 0
}

func (x *UpdateMetadataReq) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type UpdateMetadataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId int32 `protobuf:"varint,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *UpdateMetadataResp) Reset() {
	*x = UpdateMetadataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMetadataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResp) ProtoMessage() {}

func (x *UpdateMetadataResp) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResp.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResp) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetadataResp) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetUpdateResultReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId int32 `protobuf:"varint,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *GetUpdateResultReq) Reset() {
	*x = GetUpdateResultReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUpdateResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateResultReq) ProtoMessage() {}

func (x *GetUpdateResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateResultReq.ProtoReflect.Descriptor instead.
func (*GetUpdateResultReq) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{4}
}

func (x *GetUpdateResultReq) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetUpdateResultResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	End                        bool  `protobuf:"varint,1,opt,name=end,proto3" json:"end,omitempty"`
	DeviceNumber               int32 `protobuf:"varint,2,opt,name=deviceNumber,proto3" json:"deviceNumber,omitempty"`
	DeviceParamNumber          int32 `protobuf:"varint,3,opt,name=deviceParamNumber,proto3" json:"deviceParamNumber,omitempty"`
	Thread                     int32 `protobuf:"varint,4,opt,name=thread,proto3" json:"thread,omitempty"`
	Seconds                    int32 `protobuf:"varint,5,opt,name=seconds,proto3" json:"seconds,omitempty"`
	SuccessDeviceCount         int32 `protobuf:"varint,6,opt,name=successDeviceCount,proto3" json:"successDeviceCount,omitempty"`
	AverageLatencyMicroseconds int64 `protobuf:"varint,7,opt,name=averageLatencyMicroseconds,proto3" json:"averageLatencyMicroseconds,omitempty"`
}

func (x *GetUpdateResultResp) Reset() {
	*x = GetUpdateResultResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUpdateResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateResultResp) ProtoMessage() {}

func (x *GetUpdateResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateResultResp.ProtoReflect.Descriptor instead.
func (*GetUpdateResultResp) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{5}
}

func (x *GetUpdateResultResp) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}

func (x *GetUpdateResultResp) GetDeviceNumber() int32 {
	if x != nil {
		return x.DeviceNumber
	}
	return 0
}

func (x *GetUpdateResultResp) GetDeviceParamNumber() int32 {
	if x != nil {
		return x.DeviceParamNumber
	}
	return 0
}

func (x *GetUpdateResultResp) GetThread() int32 {
	if x != nil {
		return x.Thread
	}
	return 0
}

func (x *GetUpdateResultResp) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *GetUpdateResultResp) GetSuccessDeviceCount() int32 {
	if x != nil {
		return x.SuccessDeviceCount
	}
	return 0
}

func (x *GetUpdateResultResp) GetAverageLatencyMicroseconds() int64 {
	if x != nil {
		return x.AverageLatencyMicroseconds
	}
	return 0
}

type GenerateDemoDeviceDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceNumber int32 `protobuf:"varint,1,opt,name=deviceNumber,proto3" json:"deviceNumber,omitempty"`
	StartTime    int64 `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime      int64 `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *GenerateDemoDeviceDataReq) Reset() {
	*x = GenerateDemoDeviceDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDemoDeviceDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDemoDeviceDataReq) ProtoMessage() {}

func (x *GenerateDemoDeviceDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDemoDeviceDataReq.ProtoReflect.Descriptor instead.
func (*GenerateDemoDeviceDataReq) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateDemoDeviceDataReq) GetDeviceNumber() int32 {
	if x != nil {
		return x.DeviceNumber
	}
	return 0
}

func (x *GenerateDemoDeviceDataReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GenerateDemoDeviceDataReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GenerateDemoDeviceDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GenerateDemoDeviceDataResp) Reset() {
	*x = GenerateDemoDeviceDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDemoDeviceDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDemoDeviceDataResp) ProtoMessage() {}

func (x *GenerateDemoDeviceDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDemoDeviceDataResp.ProtoReflect.Descriptor instead.
func (*GenerateDemoDeviceDataResp) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateDemoDeviceDataResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_processor_proto protoreflect.FileDescriptor

var file_processor_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x22, 0x6b, 0x0a, 0x17,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x18, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x11, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22,
	0x2a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x9b, 0x02, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x1a, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1a, 0x61,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x77, 0x0a, 0x19, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x30, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x6d, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x32, 0xf4, 0x02, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x12, 0x5f, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x6d, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x6d, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x23,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x65, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_processor_proto_rawDescOnce sync.Once
	file_processor_proto_rawDescData = file_processor_proto_rawDesc
)

func file_processor_proto_rawDescGZIP() []byte {
	file_processor_proto_rawDescOnce.Do(func() {
		file_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_processor_proto_rawDescData)
	})
	return file_processor_proto_rawDescData
}

var file_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_processor_proto_goTypes = []interface{}{
	(*GenerateDemoMetadataReq)(nil),    // 0: processor.GenerateDemoMetadataReq
	(*GenerateDemoMetadataResp)(nil),   // 1: processor.GenerateDemoMetadataResp
	(*UpdateMetadataReq)(nil),          // 2: processor.UpdateMetadataReq
	(*UpdateMetadataResp)(nil),         // 3: processor.UpdateMetadataResp
	(*GetUpdateResultReq)(nil),         // 4: processor.GetUpdateResultReq
	(*GetUpdateResultResp)(nil),        // 5: processor.GetUpdateResultResp
	(*GenerateDemoDeviceDataReq)(nil),  // 6: processor.GenerateDemoDeviceDataReq
	(*GenerateDemoDeviceDataResp)(nil), // 7: processor.GenerateDemoDeviceDataResp
}
var file_processor_proto_depIdxs = []int32{
	0, // 0: processor.Processor.GenerateDemoMetadata:input_type -> processor.GenerateDemoMetadataReq
	2, // 1: processor.Processor.UpdateMetadata:input_type -> processor.UpdateMetadataReq
	4, // 2: processor.Processor.GetUpdateResult:input_type -> processor.GetUpdateResultReq
	6, // 3: processor.Processor.GenerateDemoDeviceData:input_type -> processor.GenerateDemoDeviceDataReq
	1, // 4: processor.Processor.GenerateDemoMetadata:output_type -> processor.GenerateDemoMetadataResp
	3, // 5: processor.Processor.UpdateMetadata:output_type -> processor.UpdateMetadataResp
	5, // 6: processor.Processor.GetUpdateResult:output_type -> processor.GetUpdateResultResp
	7, // 7: processor.Processor.GenerateDemoDeviceData:output_type -> processor.GenerateDemoDeviceDataResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_processor_proto_init() }
func file_processor_proto_init() {
	if File_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_processor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDemoMetadataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDemoMetadataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMetadataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMetadataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUpdateResultReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUpdateResultResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDemoDeviceDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDemoDeviceDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_processor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processor_proto_goTypes,
		DependencyIndexes: file_processor_proto_depIdxs,
		MessageInfos:      file_processor_proto_msgTypes,
	}.Build()
	File_processor_proto = out.File
	file_processor_proto_rawDesc = nil
	file_processor_proto_goTypes = nil
	file_processor_proto_depIdxs = nil
}
