// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetMetadataRequest struct {
	SN string `form:"sn"`
}

type GetMetadataResponse struct {
	Data string `json:"data"`
	Code int    `json:"code"`
}

type UpdateMetadataRequest struct {
	SN     string            `json:"sn"`
	Params map[string]string `json:"params"`
}

type UpdateMetadataResponse struct {
	Code int `json:"code"`
}
