---
mesh:
  enabled: true
ingress:
  enabled: true
services:
  - name: http
    ingress: true
    port: 80
    protocol: TCP
    targetPort: 80
    type: ClusterIP
resources:
  limits:
    memory: 250Mi
  requests:
    memory: 150Mi