// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"finishy1995/device-manager/legacy/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/metadata",
				Handler: GetMetadataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/metadata",
				Handler: UpdateMetadataHandler(serverCtx),
			},
		},
	)
}
